### ISSUE TITLE
download.py::GetObjectTask::_main : set current_index earlier in the function

### ISSUE THREAD

**Issue by guy4261** [boto/s3transfer#120]
I'm getting an error saying

```python
...
File "/usr/local/lib/python3.6/dist-packages/s3transfer/download.py", line 554, in _main
callbacks, start_index - current_index)
UnboundLocalError: local variable 'current_index' referenced before assignment
```

meaning there's an exception in the `except` clause of the `try-except` of the function.

Line 554 being https://github.com/boto/s3transfer/blob/f506f396f054d35288bcf86d5289f8749a366ccd/s3transfer/download.py#L554

And indeed, if an error is raised before `current_index = start_index` in line 530
https://github.com/boto/s3transfer/blob/develop/s3transfer/download.py#L530

then this will happen. Perhaps line 530 can be moved upwards so `current_index` gets a value? Or initialize it with `None` so that I can tell whether the exception was raised before/after line 530?

Thanks!

**Comment by jamesls** [comment]
Good catch, thanks for reporting, we'll get that fixed.

**Comment by adamhooper** [comment]
May I humbly ping: I just ran into this error, and #131 would fix it. Is there anything I can do to help?
