### ISSUE TITLE
implement presigned urls in botocore

### ISSUE THREAD

**Issue by noahrowland** [boto/s3transfer#133]
we should be able to generate presigned urls for the upload_file and upload_fileobj methods. Right now this returns:
```UnknownClientMethodError: Client does not have method: upload_fileobj```

**Comment by kyleknap** [comment]
So for the `generate_presigned_url` method, you can specify `put_object` as the method instead if you want to presign for PUT's. The `upload_file` and `upload_fileobj` are just higher level methods that wrap the lower-level `put_object` and multipart-upload operations. Would `put_object` work for your use case instead when generating presigned url's?

**Comment by kyleknap** [comment]
I noticed that you opened the issue on the `botocore` repository as well: https://github.com/boto/botocore/issues/1730. Let's keep the conversation going over in that issue as it applies more to`botocore` than `s3transfer`
