### ISSUE TITLE
ERROR: Could not install packages due to an EnvironmentError: [Errno 21] Is a directory: '/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/s3transfer-0.3.3.dist-info/METADATA'

### ISSUE THREAD

**Issue by sudhirsilwal23** [boto/s3transfer#166]
This error message is popping during installation.

Command used: pip install s3transfer

Python Version: 3.6
pip version: 20.1.1

I have already copied metadata.json in METADATA folder but still no solution.

**Comment by nateprewitt** [comment]
Hi @sudhirsilwal23, it appears something is wrong with your installation. `METADATA` is a text file, not a directory, so it should never be able to house a `metadata.json` file. We'd recommend uninstalling s3transfer completely and trying again, or starting with a fresh virtualenv.
