### ISSUE TITLE
Submission thread seems to block on unrelated tags

### ISSUE THREAD

**Issue by jamesls** [boto/s3transfer#20]
I'm working in some of the future_tag code, and I'm seeing (https://github.com/boto/s3transfer/blob/develop/s3transfer/futures.py#L328)

```python

        with self._lock:
            # Wait if there is a maximum reached
            self._wait_for_futures_to_complete_if_needed(tag)
            # Submit the task to the executor
            future = self._executor.submit(fn, *args, **kwargs)
            # Add the recently added future to the currently running futures
            self._add_future_to_currently_running(future, tag)
        return future
```

So suppose I have a max tags of `{"A": 1, "B": 1}` and sequence such as:

```
T1: submit tag A --> noblock
T1: submit tag A --> block on waiting futures
T2: submit tag B --> block on lock acquire
```

Where T1/T2 are threads and A/B are tags.  This means that even though T2 is submitting tag B which has no futures, the submission on tag B will still block on the `with self._lock` until a future for tag A completes.

**Comment by kyleknap** [comment]
Fixed with this: https://github.com/boto/s3transfer/pull/31. Closing.
