### ISSUE TITLE
Integration tests will start failing in April 2023

### ISSUE THREAD

**Issue by cfxegbert** [boto/s3transfer#262]
The integration tests use a canned ACL of 'public-read' will start failing in April 2023 according to https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

> Starting in April 2023, Amazon S3 will change the default settings for S3 Block Public Access and Object Ownership (ACLs disabled) for all new S3 buckets. For new buckets created after this update, all S3 Block Public Access settings will be enabled, and S3 access control lists (ACLs) will be disabled.

**Comment by nateprewitt** [comment]
Thanks @cfxegbert, this was resolved in #265.
