### ISSUE TITLE
readable() is inconsistent across python versions

### ISSUE THREAD

**Issue by jamesls** [boto/s3transfer#27]
I was looking to copy what `readable()` does in order to add a similar `writable()` function, but it has inconsistent behavior across python versions.  `readable()` will tell you if the file was opened readable (or rather if `read()` will actually succeed), whereas the code path in python2 will simply tell you if the fileobj has a read method, without any comment on whether or not read will fail.  Consider:

```
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
>>> from s3transfer.compat import readable
>>> readable(open('/tmp/asdfafgafdsfd', 'w'))
True

Python 3.5.1 (default, Jan 22 2016, 08:54:32)
>>> from s3transfer.compat import readable
>>> readable(open('/tmp/adfasfasdfd', 'w'))
False
```

I would expect us to try, within reason, to have consistent behavior across python versions.

**Comment by kyleknap** [comment]
Interesting. I wonder if we should just check hasattr(fileobj, 'read') and hasattr(fileobj, 'write') then. I am not sure how you would get parity with python3 other than checking if it is ``closed()`` as well?

**Comment by JordonPhillips** [comment]
This is related to the issue with `seekable`, i.e. in python 2 file objects don't have it.

**Comment by JordonPhillips** [comment]
Lacking `readable`, there's really no way to tell if you can successfully read without actually trying. For a non-seekable stream, that's a bad idea.

**Comment by jamesls** [comment]
We can have similar behavior by examining `.mode` if it's available (it's more or less what python3 does under the hood for `readable/writable`).  The question is whether or not we care to have that level of exactness.  If the file isn't opened in the correct mode for reading/writing, you'll still get an error propagated.

I think I'm leaning towards hasattr() being good enough, assuming we have good error messages now that tell you that your file isn't opened for reading/writing.

**Comment by JordonPhillips** [comment]
working on the fix

**Comment by kyleknap** [comment]
Yeah I'm leaning toward your side to @jamesls. The errror will get propogated if you cannot read from the file.

**Comment by JordonPhillips** [comment]
I would rather have the `readable` function obey its contract as much as is reasonable.

**Comment by jamesls** [comment]
What benefits does that have over just using `hasattr()` directly in the manager classes?

The benefits of just using `hasattr()`, as I see it, are that it's less code we have to maintain, and that you get the same error messages.

**Comment by jamesls** [comment]
Actually, scratch that, I think you get *worse* error messages using `readable()` than you would just using `hasattr(fileobj, 'read')`.  

Take downloads for example.  Our logic is:

```
        for download_manager_cls in download_manager_resolver_chain:
            if download_manager_cls.is_compatible(fileobj):
                return download_manager_cls
        raise RuntimeError(
            'Output %s of type: %s is not supported.' % (
                fileobj, type(fileobj)))
```

So if the file isn't opened correctly you'd get a vague `Output <open .... 'w'> of type file is not supported`.  Still enough info to figure out what went wrong, but not as explicit as a "file not opened for writing" when we try to write to the file.

**Comment by JordonPhillips** [comment]
Exactly what this issue is about. Looking for a `read` method does not guarantee readability. We could move the current code over to the manager class, which would be fine, but `is_compatible` should return correctly.

**Comment by JordonPhillips** [comment]
That sounds like we should improve our error messages, not that we shouldn't actually check for compatibility

**Comment by JordonPhillips** [comment]
Imagine we only did hasattr checks and nothing else. I pass a non-seekable object, and I get an `UnsupportedOperation` error because the seekable handler happens to come first. We would have to catch that error and move on, discarding potentially helpful information.

**Comment by jamesls** [comment]
I'm talking specifically about read/write.  I'm not suggesting we touch seekable.

Perhaps it would be helpful to show specific error messages.  I think that would sway me.

The way I see it, if we have decent error messages now, without having to write/maintain additional code, I'm not sure I see why we'd want to add additional code for readable/writeable as well as improve our error messages just to have parity with what we have now.

**Comment by JordonPhillips** [comment]
It breaks the contract of `is_compatible`. I am -1 on having code that is deliberately incorrect. It makes adding additional handlers brittle because the point we place them in the resolver chain impacts whether or not they will ever be called. It doesn't give helpful information because even in the best case it only tells you the error from the most recent handler, so you only get a subset of information. Relying solely on `hasattr('write')` is incorrect because calling `.write` on the following implementation of `io.RawIOBase` raises `NotImplementedError`:

```python
class NonWriteableFile(io.RawIOBase):
    def writeable(self):
        return False
```

Thus surfacing a python bug that we could easily avoid.

**Comment by jamesls** [comment]
@kyleknap want to weigh in?

I'm still not convinced.  I would be convinced by actual real (non hypothetical) problems this would solve.  I'll put it more concretely:  there is no public interface a customer could use right now that would result in either: a) incorrect behavior or b) incorrect/misleading error messages.  Show me sample code that says otherwise and I'm convinced.

The argument just seems to be "this is wrong because of hypothetical case X...".  The thing is, I'm not even disagreeing with it, I'm just saying it doesn't actually matter in any meaningful way right now, and I'd rather focus on other things until this is problematic.

**Comment by kyleknap** [comment]
We have been spending too much time on this.

I would prefer ``hasattr('read')``.  Given this code sample:
```py
import boto3
from s3transfer.manager import TransferManager

c = boto3.client('s3')
with TransferManager(c) as m:
    f = open('foo.py', 'w')
    future = m.upload(f, 'mybucketfoo', 'foo')
    future.result()
```

On python2, you get this (which is what it would be if we made the change to hasattr()):
```
Traceback (most recent call last):
  File "error.py", line 8, in <module>
    future.result()
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/futures.py", line 69, in result
    return self._coordinator.result()
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/futures.py", line 207, in result
    raise self._exception
IOError: File not open for reading

```
Then on python3 currently you get this:
```
raceback (most recent call last):
  File "error.py", line 8, in <module>
    future.result()
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/futures.py", line 69, in result
    return self._coordinator.result()
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/futures.py", line 207, in result
    raise self._exception
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/tasks.py", line 237, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/upload.py", line 475, in _submit
    transfer_future)(osutil, self._transfer_coordinator)
  File "/Users/kyleknap/GitHub/s3transfer/s3transfer/upload.py", line 452, in _get_upload_input_manager_cls
    fileobj, type(fileobj)))
RuntimeError: Input <_io.TextIOWrapper name='foo.py' mode='w' encoding='UTF-8'> of type: <class '_io.TextIOWrapper'> is not supported.
```
The error message for python2 is much better so that is why I am leaning toward that. So if you want to keep checking for .readable() we need to make a better error message when the resolver chain fails.

**Comment by jamesls** [comment]
Thanks, having concrete data/error messages helps.  I'm inclined to close my issue now.
