### ISSUE TITLE
Cannot upload a file-like object which outputs string data in Python 3

### ISSUE THREAD

**Issue by JordonPhillips** [boto/s3transfer#29]
We attempt to encapsulate data within a `BytesIO` which raises a `TypeError` when a string is input. So, for example, you can't upload a `StringIO`.

**Comment by kyleknap** [comment]
First I do not think this is a bug. It is a feature request and I do not think we should support this. Automatically figuring out encoding is really tricky to get right and a better interface would be one where the user provides binary as they are the only ones who truly knows what the encoding is. If we add any functionality related to automatically determining encoding, it will be a leaky at best. Closing for now.
