### ISSUE TITLE
TransferManager.download fails when file has zero bytes

### ISSUE THREAD

**Issue by mviamari** [boto/s3transfer#66]
It seems that if I attempt to download a file using a target filename, if the downloaded file has a size of zero bytes, an exception is raised.

```
import boto3, s3transfer.manager
c = boto3.client('s3')
mgr = s3transfer.manager.TransferManager(c)
f = mgr.download('test-bucket', 'zero-byte-file', '/tmp/zero-byte-file.download')
f.result()
```

raises:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../venv/lib/python2.7/site-packages/s3transfer/futures.py", line 71, in result
    return self._coordinator.result()
  File "../venv/lib/python2.7/site-packages/s3transfer/futures.py", line 220, in result
    raise self._exception
OSError: [Errno 2] No such file or directory
```

I think this is caused by `DeferredOpenFile. _open_if_needed` is never being being called since the file is zero-bytes, and there is no attempt to write to the file. And since the file is never opened, it is never created. Then when the file is renamed, it cannot be found.

This does not appear to happen in version `0.1.4`. Version `0.1.4` does not appear to have been using the `DeferredOpenFile` class for `DownloadFilenameOutputManager`

**Comment by kyleknap** [comment]
Yeah we just started noticing this as well. This PR: https://github.com/boto/s3transfer/pull/65 should fix it.

**Comment by kyleknap** [comment]
The PR got merged so it will be available in the next release of s3transfer.

**Comment by mviamari** [comment]
Great. Thanks!
