### ISSUE TITLE
README warning

### ISSUE THREAD

**Issue by johnmcteague** [boto/s3transfer#74]
Is the warning in the README still relevent (re: work in progress). s3transfer is required by boto3, do we therefore not consider boto3 1.4.x to be production ready?

We audit all OSS in our company and s3transfer is being flagged due to the warning in the README

**Comment by kyleknap** [comment]
@johnmcteague I think we need to update the README. The functionality in ``s3transfer`` is production ready as it is being used in boto3 and the AWS CLI ready. However, the interfaces may change until the library goes GA so only direct users of ``s3transfer`` should be aware of that and lock to an appropriate version if they take a direct dependency on ``s3transfer``.

**Comment by kyleknap** [comment]
I updated the README to better reflect the status of ``s3transfer``. Closing issue.
